### ISSUE TITLE
Example Code throwing NaN for Windspeed on Mine?

### ISSUE THREAD

**Issue by bwstud** [moderndevice/Wind_Sensor#1]
Hey there,

I'm running the wind sensor of an Uno for a student project. In wiring it up I accidentally ran the pin for RV to A0 and the pin for TMP to A1. No big deal, right? Just flip-flop the analogPinFor___ variables. 

I only ran it a couple times prior to extending jumper wires so I could put the sensor in a housing, but I'm now always getting NaN for windspeed, which I don't recall happening before. 

![screen shot 2015-03-17 at 11 01 48 pm](https://cloud.githubusercontent.com/assets/6791021/6703490/b340c012-ccf9-11e4-8b34-1913f4eccaf9.png)

Am I losing it? Or just missing something that's right in front of my nose? Could I have broken something in the sensor that could cause this? Running the stock example code in Arduino 1.6.1

Thanks!

**Comment by moderndevice** [comment]
Brian,

Are you running on a regulated 5 volt supply.  If the temp is too far off this can happen. 
Also you may need to set the zero wind calibration as explained in the sketch.

You may see this too if your temps are too far from 25C.

Let me know your circumstances please.

Paul Badger

**Comment by bwstud** [comment]
Figured it out! I'm an idiot, as suspected, and had a hardware issue. Now it works Swimmingly.

Thanks, for responding, Paul.
